name: docker_image_front_end_ci

# Trigger pushes on front-end directory
on:
  push:
    branches: 
      - main


# Run jobs on front-end directory

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
      working-directory: html

    name: Buils and Push
    steps:
      - uses: actions/checkout@v2.3.2
        name: Checkout