name: docker_image_front_end_ci

# Trigger pushes on front-end directory
on:
  push:
    branches: 
      - main
    paths: 
      - html/**
      - js/**

# Run jobs on front-end directory
defaults:
  run:
    working-directory: front-end

jobs:
  path-context:
    runs-on: ubuntu-latest
    name: Buils and Push
    steps:
      - uses: actions/checkout@v2.3.2
        name: Checkout